### PR TITLE
Updated Netzarbeiter_CustomerActivation to 0.5.7

### PR DESCRIPTION
**Pull request by jhoelzl**
Updated composer.lock for module Netzarbeiter_CustomerActivation from 0.5.2 to 0.5.7

### CODE REVIEW

**Comment by andrewhowdencom** [comment]
Lookin at this now. Mental notes:
```
-    public function salesCovertQuoteAddressToOrder(Varien_Event_Observer $observer)
+    public function salesConvertQuoteAddressToOrder(Varien_Event_Observer $observer)
```

**Comment by andrewhowdencom** [comment]
Hi @jhoelzl, 

On further inspection, it appears that we are bundling Netzarbeiter/CustomerActivation in the repository: 

https://github.com/sitewards/B2BProfessional/tree/master/app/code/community/Netzarbeiter/CustomerActivation

I'm not too sure how this behaves with composer; I imagine it will conflict with unless `composer install --force` is used, or something similar.

Is this a problem that you have faced previously? Can you provide some context around how you solved it? 

Cheers,

**Comment by jhoelzl** [comment]
Hi @andrewhowdencom, actually i do not understand why the complete code of Netzarbeiter_CustomerActivation is in this repo.

I would suggest to remove the code from Netzarbeiter_CustomerActivation complete from this repo and only reference it as a required package in the composer. So you do not have to care about a new version and user just can decide which verison of Netzarbeiter_CustomerActivation they prefer.

**Comment by andrewhowdencom** [comment]
Ja that does seem superior. Unfortunately I'm not well familiar with this codebase, so I cannot easily spin it up and test. I shall consult my colleagues and see if there is someone who has better knowledge of this work, so we can determine if this solution is reasonable.

This will take some time. I will try to get it done today, and if not, revisit it on Friday.

**Comment by andrewhowdencom** [comment]
After discussing with my colleagues, we have determined the best course of action is to pull down the version of the extension that is in the repo, diff them to ensure nothing was changed prior to the commit, and remove it. 

As I mentioned, this will take me some time -- I will not have anything allocatable until Friday. Alternatively, if you're happy to, I'd love to see a pull request that does this (:

Cheers!

**Comment by jhoelzl** [comment]
Okay, thanks! Take your time.

**Comment by andrewhowdencom** [comment]
Created PR: https://github.com/sitewards/B2BProfessional/pull/62

**Comment by andrewhowdencom** [comment]
@jhoelzl I shall merge this this morning, and tag it accordingly. Thank you for your contributions! It's much appreciated.

**Pull request merged**
